  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

  development:

    adapter: postgresql
    encoding: unicode
    database: wikidata_model_1
    pool: 5
    username:
    password:

  test:
    adapter: postgresql
    encoding: unicode
    database: wikidata_model_1
    pool: 5
    username:
    password:


  production:

    adapter: postgresql
    encoding: unicode
    database: wikidata_model_1
    pool: 5
    username:
    password: